/*
 * File: /Users/origami/Desktop/timvel/re-kits/utils/colors.ts
 * Project: /Users/origami/Desktop/timvel/re-kits
 * Created Date: Saturday March 2nd 2019
 * Author: Rick yang tongxue(🍔🍔) (origami@timvel.com)
 * -----
 * Last Modified: Saturday March 2nd 2019 9:16:08 pm
 * Modified By: Rick yang tongxue(🍔🍔) (origami@timvel.com)
 * -----
 */
const colors = {
  main: '#1de9b6',
  mainLight: '#a7ffeb',
  mainDep: '#004d40',
  red: '#ff8a80',
  redDep: '#b71c1c',
  redLight: '#ffcdd2',
  green: '#8bc34a',
  greenDep: '#558b2f',
  greenLight: '#dcedc8',
  amber: '#ffc107',
  white: '#fafafa',
  pureWhite: 'white',
  pureBlack: '#212121',
  backgroundGrey: '#f7f7f7',
  lightGrey: '#f5f5f5',
  midGrey: '#9e9e9e',
  depGrey: '#616161',
  transparent: 'transparent',
  pink: '#ec407a',
  purple: '#ab47bc',
  lightBlue: '#29b6f6',
  cyan: '#26c6da',
  teal: '#26a69a',
  lightGreen: '#9ccc65',
  lime: '#d4e157',
  yellow: '#ffee58',
  orange: '#ffa726',
  deepOrange: '#ff7043',
  blueGrey: '#78909c',
  grey: '#bdbdbd',
};
const colorSets = [
  colors.pink,
  colors.purple,
  colors.lightBlue,
  colors.cyan,
  colors.teal,
  colors.lightGreen,
  colors.lime,
  colors.yellow,
  colors.orange,
  colors.deepOrange,
  colors.blueGrey,
  colors.amber,
  colors.grey,
];
const colorsLight200 = {
  lightRed: '#ef9a9a',
  lightPink: '#f48fb1',
  lightPurple: '#ce93d8',
  lightDeepPurple: '#b39dd8',
  lightIndigo: '#9fa8da',
  lightBlue: '#90caf9',
  lightLightBlue: '#81d4fa',
  lightCyan: '#80deea',
  lightTeal: '#80cbc4',
  lightGreen: '#c8e6c9',
  lightLightGreen: '#c5e1a5',
  lightLime: '#e6ee9c',
  lightYellow: '#fff59d',
  lightAmber: '#ffe082',
  lightOrange: '#ffcc80',
  lightDeepOrange: '#ffab91',
  lightBrown: '#bcaaa4',
  lightGrey: '#eeeeee',
  lightBlueGrey: '#b0bec5',
};
const lightColorSet = [
  colorsLight200.lightRed,
  colorsLight200.lightPink,
  colorsLight200.lightPurple,
  colorsLight200.lightDeepPurple,
  colorsLight200.lightIndigo,
  colorsLight200.lightBlue,
  colorsLight200.lightLightBlue,
  colorsLight200.lightCyan,
  colorsLight200.lightTeal,
  colorsLight200.lightGreen,
  colorsLight200.lightLightGreen,
  colorsLight200.lightLime,
  colorsLight200.lightYellow,
  colorsLight200.lightAmber,
  colorsLight200.lightOrange,
  colorsLight200.lightDeepOrange,
  colorsLight200.lightBrown,
  colorsLight200.lightGrey,
  colorsLight200.lightBlueGrey,
];
export { colors, colorSets, lightColorSet, colorsLight200 };
